import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import RegisterForm from '../../components/forms/RegisterForm'
import SignInForm from '../../components/forms/SignInForm'
import TopNavigation from '../../components/navigation/TopNavigation'

export default function CreateProfilePage() {
    return (
        <div style={{ height: '100vh' }} className='bg-gray-50'>
            <Head>
                <title>Create profile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopNavigation profile bg={"transparent"} />
            <RegisterForm title={"Create your profile"} />
        </div>
    )
}
