import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import TopNavigation from '../../components/navigation/TopNavigation'

const categories = [

    {
        title: "popular",
        href: "/discover/popular"
    },
    {
        title: "trending",
        href: "/discover/trending"
    },
    {
        title: "blm",
        href: "/discover/blm"
    },
    {
        title: "feminism",
        href: "/discover/feminism"
    },
    {
        title: "society",
        href: "/discover/society"
    },
    {
        title: "business",
        href: "/discover/business"
    },
    {
        title: "culture",
        href: "/discover/culture"
    },
    {
        title: "spirituality",
        href: "/discover/spirituality"
    },
    {
        title: "music",
        href: "/discover/music"
    },
    {
        title: "news",
        href: "/discover/news"
    },
    {
        title: "sports",
        href: "/discover/sports"
    },
    {
        title: "education",
        href: "/discover/education"
    },
    {
        title: "fitness",
        href: "/discover/fitness"
    },
    {
        title: "health",
        href: "/discover/health"
    }

]
export default function DiscoverPage() {
    return (
        <div className='bg-white'>
            <Head>
                <title>Discover</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopNavigation />
            <div className='min-h-screen max-h-full w-full pt-[10vh]'>
                <div className='h-auto md:max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 md:py-10 py-5'>
                    <div className="grid grid-cols-4 gap-4 flex-col justify-center items-center md:py-10 py-5 w-full">
                        <div className='md:col-span-4 col-span-4'>
                            <h1 className='md:text-6xl text-3xl font-[700] md:w-[100%] w-full text-gray-800'>
                                Discover Creatives
                            </h1>
                        </div>
                        <div className='md:col-span-4 col-span-4'>
                            <div className="py-3 overflow-x-auto flex flex-nowrap border-0 w-auto hide-scroll-bar" >
                                {categories.map((category, index) => (
                                    <a
                                        key={index}
                                        href={category.href}
                                    >
                                        <span className=" 
                                        flex-shrink-0
                                px-6 py-3 rounded-full text-xl
                                font-base bg-gray-100 text-gray-800 mr-2 hover:bg-gray-200">
                                            {category.title}
                                        </span>

                                    </a>
                                ))}

                            </div>
                        </div>
                    </div>
                    {/* Start of Scrolling cards */}
                    {categories.map((category, index) =>
                        <div key={index} >
                            <h2 className='md:text-3xl text-xl font-[700] md:w-[85%] w-full text-gray-700 py-6'>{category.title}</h2>
                            <div
                                className="flex overflow-x-scroll pb-10 hide-scroll-bar"
                            >
                                <div
                                    className="flex flex-nowrap "
                                >

                                    {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((item, index) =>
                                        <div key={index}
                                            className="inline-block pr-3">
                                            <div key={index} className="w-64 h-64 max-w-xs bg-gray-50 rounded-3xl  transition-shadow duration-300"
                                                style={{
                                                    backgroundSize: 'cover',
                                                    backgroundPosition: 'center center',
                                                    backgroundImage: `url("https://storage.googleapis.com/pr-newsroom-wp/1/2022/05/SPOTIFY-PODCAST-POSTERS3-scaled.jpg")`,

                                                }}>
                                                <div className="bg-gradient-to-b 
                                from-gray-900  via-transparent  
                                to-gray-900 h-full w-full rounded-3xl flex
                                flex-col justify-between p-4">
                                                    <p className='font-semibold text-white text-xl'>Testing 123</p>
                                                    <div className='flex flex-row justify-between items-center'>

                                                        <div>
                                                            <p className='font-semibold text-white font-sm'>24 episodes</p>
                                                            <p className='font-base text-gray-400'>Content creator</p>
                                                        </div>
                                                        <button
                                                            type="button"
                                                            className="rounded-full flex flex-col 
                                                items-center justify-center h-8 w-8
                                             text-white bg-third "
                                                        >
                                                            <i className="ri-play-fill ri-lg"></i>

                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                            {/* <div
                                                className="w-64 h-64 max-w-xs 
                                                overflow-hidden 
                                                rounded-3xl shadow-0
                                                bg-gray-100 hover:shadow-md 
                                                transition-shadow duration-300 ease-in-out"
                                            ></div> */}
                                        </div>
                                    )}

                                </div>

                            </div>
                        </div>
                    )}
                    {/* End of scrolling cards */}
                </div>
            </div>
        </div>
    )
}
