import Head from 'next/head'
import Image from 'next/image'
import LandingPageHeader from '../components/headers/LandingPageHeader'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPageHeader />
      <div className='h-auto max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 md:py-10 py-5'>
        <div className="grid grid-cols-4 gap-4 flex-col justify-center items-center md:py-10 py-5">
          <div className='md:col-span-2 col-span-4'>
            <h1 className='md:text-6xl text-3xl font-[700] md:w-[85%] w-full text-gray-800'>
              Our top-tier features
            </h1>
          </div>
          <div className='md:col-span-2 col-span-4'>
            <p className='my-3 md:text-2xl text-xl text-gray-500'>
              We offer you everything you need to start earning with your audience.
              Just sign up.
            </p>
          </div>
        </div>
        <div className="grid grid-cols-3 gap-4 flex-col justify-center items-center md:py-10 py-5">
          <div className='md:col-span-1 col-span-3'>
            <div className='border border-gray-300 hover:bg-gray-200 rounded-xl p-4 h-[280px] md:h-[300px]'>
              <span className="my-3 inline-flex items-center h-12 w-12 rounded-full justify-center 
              text-3xl font-medium bg-primary">
                <i className="ri-share-circle-line"></i>
              </span>
              <h2 className='md:text-3xl text-2xl font-[700] md:w-[85%] w-full text-gray-800'>
                Public share-able link
              </h2>
              <p className='my-3 md:text-xl text-md text-gray-500'>
                Your link will be shareable across multiple channels and platforms.
                You can place it anywhere online.
              </p>
            </div>
          </div>
          <div className='md:col-span-1 col-span-3'>
            <div className='border border-gray-300 hover:bg-gray-200 rounded-xl p-4  h-[280px] md:h-[300px]'>
              <span className="my-3 inline-flex items-center h-12 w-12 rounded-full justify-center 
              text-3xl font-medium bg-primary">
                <i className="ri-profile-line"></i>
              </span>
              <h2 className='md:text-3xl text-2xl font-[700] md:w-[85%] w-full text-gray-800'>
                Your own custom profile
              </h2>
              <p className='my-3 md:text-xl text-md text-gray-500'>
                Customize your profile to match your vibe and brand colors.
              </p>
            </div>
          </div>
          <div className='md:col-span-1 col-span-3'>
            <div className='border border-gray-300 hover:bg-gray-200 rounded-xl p-4  h-[280px] md:h-[300px]'>
              <span className="my-3 inline-flex items-center h-12 w-12 rounded-full justify-center 
              text-3xl font-medium bg-primary">
                <i className="ri-price-tag-3-line"></i>
              </span>
              <h2 className='md:text-3xl text-2xl font-[700] md:w-[85%] w-full text-gray-800'>
                Custom pricing
              </h2>
              <p className='my-3 md:text-xl text-md text-gray-500'>
                Do you have multiple ad slots per episode or article ? Feel free to
                adjust pricing as you see fit.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div>

      </div>
      <div className='h-auto max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 md:py-10 py-5'>
        <h1>Discover featured podcasts</h1>
      </div>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
