import Head from 'next/head'
import Image from 'next/image'
import LandingPageHeader from '../components/headers/LandingPageHeader'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='bg-white'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingPageHeader />
      <div className='h-auto max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 md:py-10 py-5'>
        <div className="grid grid-cols-4 gap-4 flex-col justify-center items-center md:py-10 py-5">
          <div className='md:col-span-2 col-span-4'>
            <h1 className='md:text-6xl text-3xl font-[700] md:w-[85%] w-full text-gray-800'>
              Our top-tier features
            </h1>
          </div>
          <div className='md:col-span-2 col-span-4'>
            <p className='my-3 md:text-2xl text-xl text-gray-500'>
              We offer you everything you need to start earning with your audience.
              Just sign up.
            </p>
          </div>
        </div>
        <div className="grid grid-cols-3 gap-4 flex-col justify-center items-center md:py-10 py-5">
          <div className='md:col-span-1 col-span-3'>
            <div className='border border-gray-300 hover:bg-gray-100 rounded-2xl p-4 h-[280px] md:h-[300px]'>
              <span className="my-3 inline-flex items-center h-12 w-12 rounded-full justify-center 
              text-3xl font-medium bg-primary text-white">
                <i className="ri-share-circle-line"></i>
              </span>
              <h2 className='md:text-3xl text-2xl font-[700] md:w-[85%] w-full text-gray-800'>
                Public share-able link
              </h2>
              <p className='my-3 md:text-xl text-md text-gray-500'>
                Your link will be shareable across multiple channels and platforms.
                You can place it anywhere online.
              </p>
            </div>
          </div>
          <div className='md:col-span-1 col-span-3'>
            <div className='border border-gray-300 hover:bg-gray-100 rounded-2xl p-4  h-[280px] md:h-[300px]'>
              <span className="my-3 inline-flex items-center h-12 w-12 rounded-full justify-center 
              text-3xl font-medium bg-secondary text-white">
                <i className="ri-profile-line"></i>
              </span>
              <h2 className='md:text-3xl text-2xl font-[700] md:w-[85%] w-full text-gray-800'>
                Your own custom profile
              </h2>
              <p className='my-3 md:text-xl text-md text-gray-500'>
                Customize your profile to match your vibe and brand colors.
              </p>
            </div>
          </div>
          <div className='md:col-span-1 col-span-3'>
            <div className='border border-gray-300 hover:bg-gray-100 rounded-2xl p-4  h-[280px] md:h-[300px]'>
              <span className="my-3 inline-flex items-center h-12 w-12 rounded-full justify-center 
              text-3xl font-medium bg-third text-white">
                <i className="ri-price-tag-3-line"></i>
              </span>
              <h2 className='md:text-3xl text-2xl font-[700] md:w-[85%] w-full text-gray-800'>
                Custom pricing
              </h2>
              <p className='my-3 md:text-xl text-md text-gray-500'>
                Do you have multiple ad slots per episode or article ? Feel free to
                adjust pricing as you see fit.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* <div>

      </div> */}
      <div className='h-auto max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 md:py-10 py-5'>
        <h1 className='md:text-6xl text-3xl font-[700] md:w-[85%] w-full text-gray-800'>
          Pricing
        </h1>
        <p className='my-3 md:text-xl text-md text-gray-500'>
          Just one plan. For everything we have to offer.
        </p>
        <div className='grid md:grid-cols-3 grid-cols-1 gap-4 items-center md:my-10 my-5'>
          <div className='md:col-span-1 col-span-1 border border-gray-300 rounded-2xl min-h-[380px]'>
            <div className='bg-gray-100 p-6 rounded-tr-2xl rounded-tl-2xl '>
              <h2 className='md:text-3xl text-2xl font-[700] md:w-[85%] w-full text-gray-800'>
                Free
              </h2>
              <h2 className='md:text-4xl text-3xl font-[700] md:w-[85%] w-full text-gray-800'>
                € 0
              </h2>
              <p className='my-3 md:text-xl text-md text-gray-500'>
                Enough to get you started.
              </p>
            </div>
            <div className="grid grid-cols-1 gap-4 space-y-1 p-6">
              <div className='col-span-1 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4 text-2xl"></i>
                <p>A link to share everywhere</p>
              </div>
              <div className='col-span-1 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>Embedded Spotify, Youtube, Apple Music, Deezer, Twitter, Clubhouse</p>
              </div>
              <div className='col-span-1 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>All payment methods</p>
              </div>
              <div className='col-span-1 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-close-circle-fill text-red-500 mr-4  text-2xl"></i>
                <p>Custom templates</p>
              </div>
            </div>
          </div>
          <div className='md:col-span-2 col-span-1 border border-gray-300 rounded-2xl min-h-[380px]'>
            <div className='bg-secondary p-6 rounded-tr-2xl rounded-tl-2xl '>
              <h2 className='md:text-3xl text-2xl font-[700] md:w-[85%] w-full text-white'>
                Pro
              </h2>
              <h2 className='md:text-4xl text-3xl font-[700] md:w-[85%] w-full text-white'>
                € 10 <span className='text-base text-white'>per month</span>
              </h2>
              <p className='my-3 md:text-xl text-md text-white'>
                For content creators, brands and SMBs
              </p>
            </div>
            <div className="grid grid-cols-2 gap-4 space-y-1 p-6 ">
              <div className='md:col-span-1 col-span-2 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>A link to share everywhere</p>
              </div>
              <div className='md:col-span-1 col-span-2 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>Embedded Spotify, Youtube, Apple Music, Deezer, Twitter, Clubhouse</p>
              </div>
              <div className='md:col-span-1 col-span-2 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>All payment methods</p>
              </div>
              <div className='md:col-span-1 col-span-2 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>Custom templates</p>
              </div>
              <div className='md:col-span-1 col-span-2 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>Page Analytics</p>
              </div>
              <div className='md:col-span-1 col-span-2 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>SEO</p>
              </div>
              <div className='md:col-span-1 col-span-2 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>Google Analytics</p>
              </div>
              <div className='md:col-span-1 col-span-2 flex flex-row items-center text-xl h-[70px]'>
                <i className="ri-check-line text-green-500 mr-4  text-2xl"></i>
                <p>Hide Sponsorfy Logo</p>
              </div>
            </div>

          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="mx-2">
            Sponsorfy
          </span>
        </a>
      </footer>
    </div>
  )
}
