import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import TopNavigation from '../../components/navigation/TopNavigation'

export default function PricingPage() {
    return (
        <div className='bg-white'>
            <Head>
                <title>Pricing</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopNavigation profile bg={"transparent"} />
            <div className='h-screen w-screen'>
                <div className='h-auto md:max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 md:py-10 py-5 items-center flex flex-col'>
                    <h1 className='md:text-6xl text-4xl font-bold text-gray-900 py-10'>
                        Pricing
                    </h1>
                    <p className='my-3 md:text-2xl text-xl text-gray-500'>
                        Sponsio is still in alpha. <br />Create a <b>FREE</b> account and start earning money through sponsorships.
                    </p>
                    <Link href="/create-profile">
                        <button
                            type="button"
                            className="inline-flex my-5 items-center px-6 py-3 border border-transparent text-xl 
                        font-base rounded-full shadow-sm text-secondary-dark bg-secondary-light"
                        >
                            Get started for free
                        </button>
                    </Link>
                </div>
            </div>
        </div>
    )
}
