import React from 'react'
import Head from 'next/head'
import TopNavigation from '../../../components/navigation/TopNavigation'

import { useRouter } from 'next/router'
export default function CheckoutPage() {
    const { id } = useRouter().query
    return (
        <div className='bg-gray-100 min-h-screen w-screen'>
            <Head>
                <title>Checkout</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopNavigation />
            <div className="max-w-7xl pt-[10rem] mx-auto px-4 sm:px-6 lg:px-8">
                <div className='grid grid-cols-4 gap-2'>
                    <div className='col-span-4'>
                        <h1 className='text-4xl font-semibold'>Payment Details
                        </h1>
                        <h1 className='text-lg font-base text-gray-400'>Please enter your payment details to
                            complete purchase
                            <span className="text-primary mx-2">#{id}</span>
                        </h1>
                    </div>
                    <div className='md:col-span-2 col-span-4 space-y-4 bg-white p-6 md:my-4 my-2 rounded-3xl'>
                        <h3 className='text-xl font-semibold text-gray-700'>Contact information</h3>
                        <div className='space-y-2'>
                            <label htmlFor="full-name">
                                Full name <span className='text-red-500'>*</span>
                            </label>
                            <input
                                id="full-name"
                                name="name"
                                type="text"
                                autoComplete="name"
                                required
                                className="appearance-none rounded-xl h-12 relative block w-full 
                                px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900
                                 focus:z-10 text-base"
                                placeholder="Full name"
                            />
                        </div>
                        <div className='space-y-2'>
                            <label htmlFor="email-address">
                                Email address <span className='text-red-500'>*</span>
                            </label>
                            <input
                                id="email-address"
                                name="email"
                                type="email"
                                autoComplete="email"
                                required
                                className="appearance-none rounded-xl h-12 relative block w-full 
                                px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900
                                 focus:z-10 text-base"
                                placeholder="Email address"
                            />
                        </div>
                        <div className='space-y-2'>
                            <label htmlFor="email-address">
                                Phone number <span className='text-gray-500'>{`(optional)`}</span>
                            </label>
                            <input
                                id="phone"
                                name="phone"
                                type="phone"
                                autoComplete="phone"
                                required
                                className="appearance-none rounded-xl h-12 relative block w-full 
                                px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900
                                 focus:z-10 text-base"
                                placeholder="Phone number"
                            />
                        </div>
                        <div className='space-y-2'>

                        </div>

                    </div>
                    <div className='md:col-span-2 col-span-4 min-h-full p-6'>
                        <div className='space-y-2'>
                            <ul role="list" className="divide-y divide-gray-200 py-5">
                                {[1].map((person, index) => (
                                    <li key={person} className="flex">
                                        <div className='p-2 grid grid-cols-4 gap-2 w-full'>
                                            <div className='col-span-3 flex flex-col items-start justify-center space-y-3'>
                                                <p className='text-md font-base text-gray-500'>Item #{index + 1}</p>
                                                <p className='text-xl font-medium'>30 seconds at start</p>
                                                <p className='text-sm text-gray-500'>This ad would be at the start of the podcast</p>
                                            </div>
                                            <div className='col-span-1 flex flex-col items-end justify-center'>
                                                <p className='text-lg'>€40</p>
                                            </div>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                            <div className='h-1 bg-gray-900' />
                            <div className='flex flex-col items-end justify-center'>
                                <div className='p-2 grid grid-cols-4 gap-2 w-full'>
                                    <div className='col-span-3 flex flex-col items-start justify-center space-y-3'>
                                        <p className='text-lg font-medium'>Sum</p>
                                    </div>
                                    <div className='col-span-1 flex flex-col items-end justify-center'>
                                        <p className='text-lg text-gray-900'>€40</p>
                                    </div>
                                </div>
                                <div className='p-2 grid grid-cols-4 gap-2 w-full'>
                                    <div className='col-span-3 flex flex-col items-start justify-center space-y-3'>
                                        <p className='text-sm text-gray-400'>Service fee</p>
                                    </div>
                                    <div className='col-span-1 flex flex-col items-end justify-center'>
                                        <p className='text-sm text-green-400'>+ €2.99</p>
                                    </div>
                                </div>
                                <div className='p-2 grid grid-cols-4 gap-2 w-full'>
                                    <div className='col-span-3 flex flex-col items-start justify-center space-y-3'>
                                        <p className='text-2xl font-bold'>Total amount</p>
                                    </div>
                                    <div className='col-span-1 flex flex-col items-end justify-center'>
                                        <p className='text-2xl font-bold text-gray-900'>€42.99</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className='my-4 flex flex-col items-end justify-center'>
                            <button
                                type="button"
                                className="col-span-2 inline-flex justify-center 
                                items-center  w-full px-3 py-1.5 border border-transparent text-xl font-medium rounded-full shadow-sm 
                        text-white bg-green-500 focus:outline-none 
                        focus:ring-2 focus:ring-offset-2 focus:ring-primary-800"
                            >
                                Pay
                            </button>
                            <p className='text-sm my-3'>
                                A payment link will be visible in the next screen and also emailed to
                                complete your purchase right now or at a later time.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
